export default {
  LOADING_RAIN: "LOADING_RAIN",
  FETCH_RAIN: "FETCH_RAIN",
  ERROR_RAIN: "ERROR_RAIN",
  CLEAR_ERROR_RAIN: "CLEAR_ERROR_RAIN",
  LOADING_STATIONS: "LOADING_STATIONS",
  FETCH_STATIONS: "FETCH_STATIONS",
  ERROR_STATIONS: "ERROR_STATIONS"
};
